# Generated by Django 5.0.3 on 2024-03-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_session_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Session_Year',
        ),
    ]
