# Generated by Django 5.0.3 on 2024-04-05 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Course_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session_year_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
